### ISSUE TITLE
App won't failover to XHR if WebSockets are down

### ISSUE THREAD

**Issue by gcollazo** [blimpllc/boards-web#1]
The app should failover to XHR if for some reason the WebSocket connection can't be initiated.

```
GET http://0.0.0.0:8080/ws/api/info net::ERR_CONNECTION_REFUSED
ConnectionError: code 1002, reason Can't connect to server, type close
```

We must implement a test as part of the suite to check if the web app can talk with the server through both services XHR and WebSockets.

**Comment by elving** [comment]
This issue was due to `sockjs`. We are now using `socketio` and managing Websocket connection failure in a different way: https://github.com/GetBlimp/boards-web/commit/06104bfbc17c26eccaaff662be679819cc4b1622.
